title: Recursion Lab
description: Recursion Lab is a project dedicated to the study of self-similarity and feedback-related phenomena
show_downloads: true
google_analytics:
theme: jekyll-theme-tactile
